/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_menu_Admin (void)
{
  GtkWidget *menu_Admin;
  GtkWidget *hbox1;
  GtkWidget *fixed7;
  GtkWidget *label105;
  GtkWidget *btnGestionAgent;
  GtkWidget *btnGestionCompte;
  GtkWidget *btnGestionService;
  GtkWidget *btnParking;
  GtkWidget *image52;

  menu_Admin = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (menu_Admin), _("Menu"));
  gtk_window_set_position (GTK_WINDOW (menu_Admin), GTK_WIN_POS_CENTER_ON_PARENT);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (menu_Admin), hbox1);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_box_pack_start (GTK_BOX (hbox1), fixed7, TRUE, TRUE, 0);

  label105 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"medium\">  Menu Administrateur  </span></u>"));
  gtk_widget_show (label105);
  gtk_fixed_put (GTK_FIXED (fixed7), label105, 304, 24);
  gtk_widget_set_size_request (label105, 225, 32);
  gtk_label_set_use_markup (GTK_LABEL (label105), TRUE);

  btnGestionAgent = gtk_button_new_with_mnemonic (_("Gestion des Agents"));
  gtk_widget_show (btnGestionAgent);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionAgent, 312, 80);
  gtk_widget_set_size_request (btnGestionAgent, 202, 37);

  btnGestionCompte = gtk_button_new_with_mnemonic (_("Gestion des Comptes"));
  gtk_widget_show (btnGestionCompte);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionCompte, 312, 144);
  gtk_widget_set_size_request (btnGestionCompte, 202, 37);

  btnGestionService = gtk_button_new_with_mnemonic (_("Gestion des Services "));
  gtk_widget_show (btnGestionService);
  gtk_fixed_put (GTK_FIXED (fixed7), btnGestionService, 312, 280);
  gtk_widget_set_size_request (btnGestionService, 202, 37);

  btnParking = gtk_button_new_with_mnemonic (_("Gestion de Parking"));
  gtk_widget_show (btnParking);
  gtk_fixed_put (GTK_FIXED (fixed7), btnParking, 312, 208);
  gtk_widget_set_size_request (btnParking, 202, 37);

  image52 = create_pixmap (menu_Admin, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image52);
  gtk_fixed_put (GTK_FIXED (fixed7), image52, 40, 80);
  gtk_widget_set_size_request (image52, 240, 208);

  g_signal_connect ((gpointer) btnGestionAgent, "clicked",
                    G_CALLBACK (on_btnGestionAgent_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionCompte, "clicked",
                    G_CALLBACK (on_btnGestionCompte_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionService, "clicked",
                    G_CALLBACK (on_btnGestionService_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnParking, "clicked",
                    G_CALLBACK (on_btnParking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (menu_Admin, menu_Admin, "menu_Admin");
  GLADE_HOOKUP_OBJECT (menu_Admin, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (menu_Admin, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (menu_Admin, label105, "label105");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionAgent, "btnGestionAgent");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionCompte, "btnGestionCompte");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnGestionService, "btnGestionService");
  GLADE_HOOKUP_OBJECT (menu_Admin, btnParking, "btnParking");
  GLADE_HOOKUP_OBJECT (menu_Admin, image52, "image52");

  return menu_Admin;
}

GtkWidget*
create_Modification (void)
{
  GtkWidget *Modification;
  GtkWidget *fixed3;
  GtkObject *spinMinuteModRes_adj;
  GtkWidget *spinMinuteModRes;
  GtkObject *spinDureeModRes_adj;
  GtkWidget *spinDureeModRes;
  GtkObject *spinJourModRes_adj;
  GtkWidget *spinJourModRes;
  GtkObject *spinMoisModRes_adj;
  GtkWidget *spinMoisModRes;
  GtkObject *spinAnneeModRes_adj;
  GtkWidget *spinAnneeModRes;
  GtkObject *spinHeureModRes_adj;
  GtkWidget *spinHeureModRes;
  GtkWidget *label40;
  GtkWidget *label41;
  GtkWidget *label42;
  GtkWidget *label43;
  GtkWidget *radioHeureModRes;
  GSList *radioHeureModRes_group = NULL;
  GtkWidget *radioJourModRes;
  GtkWidget *btnModifierRes;
  GtkWidget *alignment14;
  GtkWidget *hbox20;
  GtkWidget *image16;
  GtkWidget *label45;
  GtkWidget *labelErreurM;
  GtkWidget *btnAnnulerModRes;
  GtkWidget *alignment15;
  GtkWidget *hbox21;
  GtkWidget *image17;
  GtkWidget *label46;
  GtkWidget *image41;
  GtkWidget *label38;

  Modification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modification), _("Modification de la reservation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Modification), fixed3);

  spinMinuteModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMinuteModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMinuteModRes_adj), 1, 0);
  gtk_widget_show (spinMinuteModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinMinuteModRes, 160, 200);
  gtk_widget_set_size_request (spinMinuteModRes, 192, 24);

  spinDureeModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinDureeModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinDureeModRes_adj), 1, 0);
  gtk_widget_show (spinDureeModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinDureeModRes, 112, 256);
  gtk_widget_set_size_request (spinDureeModRes, 96, 24);

  spinJourModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJourModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourModRes_adj), 1, 0);
  gtk_widget_show (spinJourModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinJourModRes, 136, 72);
  gtk_widget_set_size_request (spinJourModRes, 60, 27);

  spinMoisModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMoisModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisModRes_adj), 1, 0);
  gtk_widget_show (spinMoisModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinMoisModRes, 208, 72);
  gtk_widget_set_size_request (spinMoisModRes, 60, 27);

  spinAnneeModRes_adj = gtk_adjustment_new (1, 0, 2090, 1, 10, 10);
  spinAnneeModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeModRes_adj), 1, 0);
  gtk_widget_show (spinAnneeModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinAnneeModRes, 288, 72);
  gtk_widget_set_size_request (spinAnneeModRes, 60, 27);

  spinHeureModRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinHeureModRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinHeureModRes_adj), 1, 0);
  gtk_widget_show (spinHeureModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), spinHeureModRes, 152, 144);
  gtk_widget_set_size_request (spinHeureModRes, 200, 24);

  label40 = gtk_label_new (_("Date_Debut : "));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed3), label40, 40, 72);
  gtk_widget_set_size_request (label40, 96, 24);

  label41 = gtk_label_new (_("Heure_debut : "));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed3), label41, 40, 136);
  gtk_widget_set_size_request (label41, 104, 32);

  label42 = gtk_label_new (_("Minutes_debut : "));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed3), label42, 32, 184);
  gtk_widget_set_size_request (label42, 120, 40);

  label43 = gtk_label_new (_("Dur\303\251e : "));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed3), label43, 40, 256);
  gtk_widget_set_size_request (label43, 80, 24);

  radioHeureModRes = gtk_radio_button_new_with_mnemonic (NULL, _("Heures"));
  gtk_widget_show (radioHeureModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), radioHeureModRes, 216, 256);
  gtk_widget_set_size_request (radioHeureModRes, 88, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHeureModRes), radioHeureModRes_group);
  radioHeureModRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHeureModRes));

  radioJourModRes = gtk_radio_button_new_with_mnemonic (NULL, _("Jours"));
  gtk_widget_show (radioJourModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), radioJourModRes, 312, 256);
  gtk_widget_set_size_request (radioJourModRes, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJourModRes), radioHeureModRes_group);
  radioHeureModRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJourModRes));

  btnModifierRes = gtk_button_new ();
  gtk_widget_show (btnModifierRes);
  gtk_fixed_put (GTK_FIXED (fixed3), btnModifierRes, 48, 344);
  gtk_widget_set_size_request (btnModifierRes, 104, 40);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (btnModifierRes), alignment14);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox20);

  image16 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox20), image16, FALSE, FALSE, 0);

  label45 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox20), label45, FALSE, FALSE, 0);

  labelErreurM = gtk_label_new ("");
  gtk_widget_show (labelErreurM);
  gtk_fixed_put (GTK_FIXED (fixed3), labelErreurM, 88, 424);
  gtk_widget_set_size_request (labelErreurM, 272, 24);

  btnAnnulerModRes = gtk_button_new ();
  gtk_widget_show (btnAnnulerModRes);
  gtk_fixed_put (GTK_FIXED (fixed3), btnAnnulerModRes, 272, 344);
  gtk_widget_set_size_request (btnAnnulerModRes, 96, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (btnAnnulerModRes), alignment15);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox21);

  image17 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox21), image17, FALSE, FALSE, 0);

  label46 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label46);
  gtk_box_pack_start (GTK_BOX (hbox21), label46, FALSE, FALSE, 0);

  image41 = create_pixmap (Modification, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (fixed3), image41, 400, 72);
  gtk_widget_set_size_request (image41, 280, 208);

  label38 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Modifier Reservation   </span></u>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed3), label38, 120, 8);
  gtk_widget_set_size_request (label38, 360, 48);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  g_signal_connect ((gpointer) radioHeureModRes, "toggled",
                    G_CALLBACK (on_radioHeureModRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJourModRes, "toggled",
                    G_CALLBACK (on_radioJourModRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnModifierRes, "clicked",
                    G_CALLBACK (on_btnModifierRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerModRes, "clicked",
                    G_CALLBACK (on_btnAnnulerModRes_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modification, Modification, "Modification");
  GLADE_HOOKUP_OBJECT (Modification, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Modification, spinMinuteModRes, "spinMinuteModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinDureeModRes, "spinDureeModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinJourModRes, "spinJourModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinMoisModRes, "spinMoisModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinAnneeModRes, "spinAnneeModRes");
  GLADE_HOOKUP_OBJECT (Modification, spinHeureModRes, "spinHeureModRes");
  GLADE_HOOKUP_OBJECT (Modification, label40, "label40");
  GLADE_HOOKUP_OBJECT (Modification, label41, "label41");
  GLADE_HOOKUP_OBJECT (Modification, label42, "label42");
  GLADE_HOOKUP_OBJECT (Modification, label43, "label43");
  GLADE_HOOKUP_OBJECT (Modification, radioHeureModRes, "radioHeureModRes");
  GLADE_HOOKUP_OBJECT (Modification, radioJourModRes, "radioJourModRes");
  GLADE_HOOKUP_OBJECT (Modification, btnModifierRes, "btnModifierRes");
  GLADE_HOOKUP_OBJECT (Modification, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Modification, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Modification, image16, "image16");
  GLADE_HOOKUP_OBJECT (Modification, label45, "label45");
  GLADE_HOOKUP_OBJECT (Modification, labelErreurM, "labelErreurM");
  GLADE_HOOKUP_OBJECT (Modification, btnAnnulerModRes, "btnAnnulerModRes");
  GLADE_HOOKUP_OBJECT (Modification, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Modification, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Modification, image17, "image17");
  GLADE_HOOKUP_OBJECT (Modification, label46, "label46");
  GLADE_HOOKUP_OBJECT (Modification, image41, "image41");
  GLADE_HOOKUP_OBJECT (Modification, label38, "label38");

  return Modification;
}

GtkWidget*
create_Menu_User (void)
{
  GtkWidget *Menu_User;
  GtkWidget *fixed4;
  GtkWidget *hbuttonbox7;
  GtkWidget *btnAfficherFactureM;
  GtkWidget *alignment38;
  GtkWidget *hbox44;
  GtkWidget *image40;
  GtkWidget *label94;
  GtkWidget *btnGestionAvis;
  GtkWidget *btnGestionReservation;
  GtkWidget *label44;
  GtkWidget *image15;

  Menu_User = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Menu_User), _("Menu Utilisateur"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Menu_User), fixed4);

  hbuttonbox7 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox7);
  gtk_fixed_put (GTK_FIXED (fixed4), hbuttonbox7, 216, 168);
  gtk_widget_set_size_request (hbuttonbox7, 170, 29);

  btnAfficherFactureM = gtk_button_new ();
  gtk_widget_show (btnAfficherFactureM);
  gtk_fixed_put (GTK_FIXED (fixed4), btnAfficherFactureM, 344, 288);
  gtk_widget_set_size_request (btnAfficherFactureM, 208, 29);

  alignment38 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment38);
  gtk_container_add (GTK_CONTAINER (btnAfficherFactureM), alignment38);

  hbox44 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox44);
  gtk_container_add (GTK_CONTAINER (alignment38), hbox44);

  image40 = gtk_image_new_from_stock ("gtk-print", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image40);
  gtk_box_pack_start (GTK_BOX (hbox44), image40, FALSE, FALSE, 0);

  label94 = gtk_label_new_with_mnemonic (_("Afficher Facture Mensuelle"));
  gtk_widget_show (label94);
  gtk_box_pack_start (GTK_BOX (hbox44), label94, FALSE, FALSE, 0);

  btnGestionAvis = gtk_button_new_with_mnemonic (_("Gestion des Avis et Reclamations"));
  gtk_widget_show (btnGestionAvis);
  gtk_fixed_put (GTK_FIXED (fixed4), btnGestionAvis, 336, 216);
  gtk_widget_set_size_request (btnGestionAvis, 240, 32);

  btnGestionReservation = gtk_button_new_with_mnemonic (_("Gestion Des Reservation"));
  gtk_widget_show (btnGestionReservation);
  gtk_fixed_put (GTK_FIXED (fixed4), btnGestionReservation, 360, 144);
  gtk_widget_set_size_request (btnGestionReservation, 176, 32);

  label44 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"medium\">  Menu Utilisateur   </span></u>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed4), label44, 344, 48);
  gtk_widget_set_size_request (label44, 208, 32);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  image15 = create_pixmap (Menu_User, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image15);
  gtk_fixed_put (GTK_FIXED (fixed4), image15, 0, 16);
  gtk_widget_set_size_request (image15, 368, 424);

  g_signal_connect ((gpointer) btnAfficherFactureM, "clicked",
                    G_CALLBACK (on_btnAfficherFactureM_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionAvis, "clicked",
                    G_CALLBACK (on_btnGestionAvis_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnGestionReservation, "clicked",
                    G_CALLBACK (on_btnGestionReservation_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Menu_User, Menu_User, "Menu_User");
  GLADE_HOOKUP_OBJECT (Menu_User, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Menu_User, hbuttonbox7, "hbuttonbox7");
  GLADE_HOOKUP_OBJECT (Menu_User, btnAfficherFactureM, "btnAfficherFactureM");
  GLADE_HOOKUP_OBJECT (Menu_User, alignment38, "alignment38");
  GLADE_HOOKUP_OBJECT (Menu_User, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (Menu_User, image40, "image40");
  GLADE_HOOKUP_OBJECT (Menu_User, label94, "label94");
  GLADE_HOOKUP_OBJECT (Menu_User, btnGestionAvis, "btnGestionAvis");
  GLADE_HOOKUP_OBJECT (Menu_User, btnGestionReservation, "btnGestionReservation");
  GLADE_HOOKUP_OBJECT (Menu_User, label44, "label44");
  GLADE_HOOKUP_OBJECT (Menu_User, image15, "image15");

  return Menu_User;
}

GtkWidget*
create_Ajouter_Reservation (void)
{
  GtkWidget *Ajouter_Reservation;
  GtkWidget *_;
  GtkObject *spinJourRes_adj;
  GtkWidget *spinJourRes;
  GtkObject *spinMoisRes_adj;
  GtkWidget *spinMoisRes;
  GtkObject *spinAnneeRes_adj;
  GtkWidget *spinAnneeRes;
  GtkWidget *label61;
  GtkObject *spinHeureRes_adj;
  GtkWidget *spinHeureRes;
  GtkWidget *label62;
  GtkObject *spinMinuteRes_adj;
  GtkWidget *spinMinuteRes;
  GtkObject *spinDureeRes_adj;
  GtkWidget *spinDureeRes;
  GtkWidget *label63;
  GtkWidget *entryIdRes;
  GtkWidget *label85;
  GtkWidget *tvParkingA;
  GtkWidget *label59;
  GtkWidget *label86;
  GtkWidget *btnAnnulerAdd;
  GtkWidget *alignment25;
  GtkWidget *hbox31;
  GtkWidget *image27;
  GtkWidget *btnAnnuler;
  GtkWidget *label60;
  GtkWidget *labelErreur;
  GtkWidget *radioHeureRes;
  GSList *radioHeureRes_group = NULL;
  GtkWidget *radioJourRes;
  GtkWidget *btnAjouterRes;
  GtkWidget *alignment37;
  GtkWidget *hbox43;
  GtkWidget *image39;
  GtkWidget *label92;
  GtkWidget *comboRegion;
  GtkWidget *btnSearchPark;
  GtkWidget *alignment36;
  GtkWidget *hbox42;
  GtkWidget *image38;
  GtkWidget *label91;
  GtkWidget *image43;
  GtkWidget *label58;

  Ajouter_Reservation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_Reservation), _("Nouvelle Reservation"));

  _ = gtk_fixed_new ();
  gtk_widget_show (_);
  gtk_container_add (GTK_CONTAINER (Ajouter_Reservation), _);

  spinJourRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinJourRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourRes_adj), 1, 0);
  gtk_widget_show (spinJourRes);
  gtk_fixed_put (GTK_FIXED (_), spinJourRes, 160, 128);
  gtk_widget_set_size_request (spinJourRes, 60, 27);

  spinMoisRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMoisRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisRes_adj), 1, 0);
  gtk_widget_show (spinMoisRes);
  gtk_fixed_put (GTK_FIXED (_), spinMoisRes, 232, 128);
  gtk_widget_set_size_request (spinMoisRes, 60, 27);

  spinAnneeRes_adj = gtk_adjustment_new (2024, 0, 2090, 1, 10, 10);
  spinAnneeRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeRes_adj), 0, 0);
  gtk_widget_show (spinAnneeRes);
  gtk_fixed_put (GTK_FIXED (_), spinAnneeRes, 312, 128);
  gtk_widget_set_size_request (spinAnneeRes, 60, 27);

  label61 = gtk_label_new (_("Heure_Debut : "));
  gtk_widget_show (label61);
  gtk_fixed_put (GTK_FIXED (_), label61, 48, 208);
  gtk_widget_set_size_request (label61, 112, 24);

  spinHeureRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinHeureRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinHeureRes_adj), 1, 0);
  gtk_widget_show (spinHeureRes);
  gtk_fixed_put (GTK_FIXED (_), spinHeureRes, 168, 208);
  gtk_widget_set_size_request (spinHeureRes, 144, 24);

  label62 = gtk_label_new (_("Minute_Debut : "));
  gtk_widget_show (label62);
  gtk_fixed_put (GTK_FIXED (_), label62, 56, 272);
  gtk_widget_set_size_request (label62, 112, 24);

  spinMinuteRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinMinuteRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinMinuteRes_adj), 1, 0);
  gtk_widget_show (spinMinuteRes);
  gtk_fixed_put (GTK_FIXED (_), spinMinuteRes, 176, 272);
  gtk_widget_set_size_request (spinMinuteRes, 152, 24);

  spinDureeRes_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  spinDureeRes = gtk_spin_button_new (GTK_ADJUSTMENT (spinDureeRes_adj), 1, 0);
  gtk_widget_show (spinDureeRes);
  gtk_fixed_put (GTK_FIXED (_), spinDureeRes, 136, 344);
  gtk_widget_set_size_request (spinDureeRes, 144, 24);

  label63 = gtk_label_new (_("Duree : "));
  gtk_widget_show (label63);
  gtk_fixed_put (GTK_FIXED (_), label63, 64, 352);
  gtk_widget_set_size_request (label63, 49, 17);

  entryIdRes = gtk_entry_new ();
  gtk_widget_show (entryIdRes);
  gtk_fixed_put (GTK_FIXED (_), entryIdRes, 200, 72);
  gtk_widget_set_size_request (entryIdRes, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryIdRes), 8226);

  label85 = gtk_label_new (_("Region du Parking : "));
  gtk_widget_show (label85);
  gtk_fixed_put (GTK_FIXED (_), label85, 56, 424);
  gtk_widget_set_size_request (label85, 144, 24);

  tvParkingA = gtk_tree_view_new ();
  gtk_widget_show (tvParkingA);
  gtk_fixed_put (GTK_FIXED (_), tvParkingA, 64, 528);
  gtk_widget_set_size_request (tvParkingA, 456, 136);

  label59 = gtk_label_new (_("ID de la Reservation : "));
  gtk_widget_show (label59);
  gtk_fixed_put (GTK_FIXED (_), label59, 40, 72);
  gtk_widget_set_size_request (label59, 160, 24);

  label86 = gtk_label_new (_("Parking disponible"));
  gtk_widget_show (label86);
  gtk_fixed_put (GTK_FIXED (_), label86, 128, 488);
  gtk_widget_set_size_request (label86, 168, 24);

  btnAnnulerAdd = gtk_button_new ();
  gtk_widget_show (btnAnnulerAdd);
  gtk_fixed_put (GTK_FIXED (_), btnAnnulerAdd, 32, 680);
  gtk_widget_set_size_request (btnAnnulerAdd, 96, 29);

  alignment25 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment25);
  gtk_container_add (GTK_CONTAINER (btnAnnulerAdd), alignment25);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment25), hbox31);

  image27 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox31), image27, FALSE, FALSE, 0);

  btnAnnuler = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (btnAnnuler);
  gtk_box_pack_start (GTK_BOX (hbox31), btnAnnuler, FALSE, FALSE, 0);

  label60 = gtk_label_new (_("Date_Debut : "));
  gtk_widget_show (label60);
  gtk_fixed_put (GTK_FIXED (_), label60, 48, 136);
  gtk_widget_set_size_request (label60, 104, 24);

  labelErreur = gtk_label_new ("");
  gtk_widget_show (labelErreur);
  gtk_fixed_put (GTK_FIXED (_), labelErreur, 96, 712);
  gtk_widget_set_size_request (labelErreur, 320, 24);

  radioHeureRes = gtk_radio_button_new_with_mnemonic (NULL, _("Heure"));
  gtk_widget_show (radioHeureRes);
  gtk_fixed_put (GTK_FIXED (_), radioHeureRes, 288, 344);
  gtk_widget_set_size_request (radioHeureRes, 72, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioHeureRes), radioHeureRes_group);
  radioHeureRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioHeureRes));

  radioJourRes = gtk_radio_button_new_with_mnemonic (NULL, _("Jour"));
  gtk_widget_show (radioJourRes);
  gtk_fixed_put (GTK_FIXED (_), radioJourRes, 360, 344);
  gtk_widget_set_size_request (radioJourRes, 64, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radioJourRes), radioHeureRes_group);
  radioHeureRes_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radioJourRes));

  btnAjouterRes = gtk_button_new ();
  gtk_widget_show (btnAjouterRes);
  gtk_fixed_put (GTK_FIXED (_), btnAjouterRes, 368, 680);
  gtk_widget_set_size_request (btnAjouterRes, 96, 29);

  alignment37 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment37);
  gtk_container_add (GTK_CONTAINER (btnAjouterRes), alignment37);

  hbox43 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox43);
  gtk_container_add (GTK_CONTAINER (alignment37), hbox43);

  image39 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox43), image39, FALSE, FALSE, 0);

  label92 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label92);
  gtk_box_pack_start (GTK_BOX (hbox43), label92, FALSE, FALSE, 0);

  comboRegion = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboRegion);
  gtk_fixed_put (GTK_FIXED (_), comboRegion, 208, 416);
  gtk_widget_set_size_request (comboRegion, 237, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Sidi_Bousaid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("El_Manzeh"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Lac1"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Lac2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Marsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Carthage"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Zone_Indus_Manouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Centre_ville_Ben_Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Azur_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Tunis_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Manar_City"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboRegion), _("Tunisia_Mal"));

  btnSearchPark = gtk_button_new ();
  gtk_widget_show (btnSearchPark);
  gtk_fixed_put (GTK_FIXED (_), btnSearchPark, 456, 416);
  gtk_widget_set_size_request (btnSearchPark, 112, 32);

  alignment36 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment36);
  gtk_container_add (GTK_CONTAINER (btnSearchPark), alignment36);

  hbox42 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox42);
  gtk_container_add (GTK_CONTAINER (alignment36), hbox42);

  image38 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_box_pack_start (GTK_BOX (hbox42), image38, FALSE, FALSE, 0);

  label91 = gtk_label_new_with_mnemonic (_("Rechercher\n"));
  gtk_widget_show (label91);
  gtk_box_pack_start (GTK_BOX (hbox42), label91, FALSE, FALSE, 0);

  image43 = create_pixmap (Ajouter_Reservation, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image43);
  gtk_fixed_put (GTK_FIXED (_), image43, 448, 112);
  gtk_widget_set_size_request (image43, 248, 208);

  label58 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Ajouter une nouvelle Reservation    </span></u>"));
  gtk_widget_show (label58);
  gtk_fixed_put (GTK_FIXED (_), label58, 104, 16);
  gtk_widget_set_size_request (label58, 480, 32);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  g_signal_connect ((gpointer) tvParkingA, "row_activated",
                    G_CALLBACK (on_tvParkingA_row_activated),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerAdd, "clicked",
                    G_CALLBACK (on_btnAnnulerAdd_clicked),
                    NULL);
  g_signal_connect ((gpointer) radioHeureRes, "toggled",
                    G_CALLBACK (on_radioHeureRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) radioJourRes, "toggled",
                    G_CALLBACK (on_radioJourRes_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnAjouterRes, "clicked",
                    G_CALLBACK (on_btnAjouterRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnSearchPark, "clicked",
                    G_CALLBACK (on_btnSearchPark_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_Reservation, Ajouter_Reservation, "Ajouter_Reservation");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, _, "_");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinJourRes, "spinJourRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinMoisRes, "spinMoisRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinAnneeRes, "spinAnneeRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label61, "label61");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinHeureRes, "spinHeureRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label62, "label62");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinMinuteRes, "spinMinuteRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, spinDureeRes, "spinDureeRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label63, "label63");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, entryIdRes, "entryIdRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label85, "label85");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, tvParkingA, "tvParkingA");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label59, "label59");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label86, "label86");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAnnulerAdd, "btnAnnulerAdd");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment25, "alignment25");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image27, "image27");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAnnuler, "btnAnnuler");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label60, "label60");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, labelErreur, "labelErreur");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, radioHeureRes, "radioHeureRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, radioJourRes, "radioJourRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnAjouterRes, "btnAjouterRes");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment37, "alignment37");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox43, "hbox43");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image39, "image39");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label92, "label92");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, comboRegion, "comboRegion");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, btnSearchPark, "btnSearchPark");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, alignment36, "alignment36");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, hbox42, "hbox42");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image38, "image38");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label91, "label91");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, image43, "image43");
  GLADE_HOOKUP_OBJECT (Ajouter_Reservation, label58, "label58");

  return Ajouter_Reservation;
}

GtkWidget*
create_Reservations_Listes (void)
{
  GtkWidget *Reservations_Listes;
  GtkWidget *fixed6;
  GtkWidget *label97;
  GtkWidget *label98;
  GtkObject *spinJourFl_adj;
  GtkWidget *spinJourFl;
  GtkObject *spinMoisFl_adj;
  GtkWidget *spinMoisFl;
  GtkObject *spinAnneeFl_adj;
  GtkWidget *spinAnneeFl;
  GtkWidget *tvReservation;
  GtkWidget *image50;
  GtkWidget *comboEtat;
  GtkWidget *checkStatus;
  GtkWidget *checkDateDebut;
  GtkWidget *label96;
  GtkWidget *btnFiltreRes;
  GtkWidget *alignment39;
  GtkWidget *hbox45;
  GtkWidget *image44;
  GtkWidget *label95;
  GtkWidget *btnTriRes;
  GtkWidget *alignment40;
  GtkWidget *hbox46;
  GtkWidget *image45;
  GtkWidget *label99;
  GtkWidget *btnAjouterFl;
  GtkWidget *alignment41;
  GtkWidget *hbox47;
  GtkWidget *image46;
  GtkWidget *label100;
  GtkWidget *btnModifierFl;
  GtkWidget *alignment45;
  GtkWidget *hbox51;
  GtkWidget *image51;
  GtkWidget *label104;
  GtkWidget *btnAnnulerRes;
  GtkWidget *alignment43;
  GtkWidget *hbox49;
  GtkWidget *image48;
  GtkWidget *label102;
  GtkWidget *btnSupprimerFl;
  GtkWidget *alignment44;
  GtkWidget *hbox50;
  GtkWidget *image49;
  GtkWidget *label103;
  GtkWidget *btnAcceuilFl;
  GtkWidget *alignment46;
  GtkWidget *hbox52;
  GtkWidget *image53;
  GtkWidget *label106;

  Reservations_Listes = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Reservations_Listes), _("Reservations Listes"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Reservations_Listes), fixed6);

  label97 = gtk_label_new (_("Status : "));
  gtk_widget_show (label97);
  gtk_fixed_put (GTK_FIXED (fixed6), label97, 456, 96);
  gtk_widget_set_size_request (label97, 72, 25);

  label98 = gtk_label_new (_("Date Debut : "));
  gtk_widget_show (label98);
  gtk_fixed_put (GTK_FIXED (fixed6), label98, 448, 136);
  gtk_widget_set_size_request (label98, 120, 25);

  spinJourFl_adj = gtk_adjustment_new (1, 0, 31, 1, 10, 10);
  spinJourFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinJourFl_adj), 1, 0);
  gtk_widget_show (spinJourFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinJourFl, 592, 136);
  gtk_widget_set_size_request (spinJourFl, 60, 27);

  spinMoisFl_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  spinMoisFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinMoisFl_adj), 1, 0);
  gtk_widget_show (spinMoisFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinMoisFl, 672, 136);
  gtk_widget_set_size_request (spinMoisFl, 60, 27);

  spinAnneeFl_adj = gtk_adjustment_new (2024, 2024, 2090, 1, 10, 10);
  spinAnneeFl = gtk_spin_button_new (GTK_ADJUSTMENT (spinAnneeFl_adj), 1, 0);
  gtk_widget_show (spinAnneeFl);
  gtk_fixed_put (GTK_FIXED (fixed6), spinAnneeFl, 760, 136);
  gtk_widget_set_size_request (spinAnneeFl, 60, 27);

  tvReservation = gtk_tree_view_new ();
  gtk_widget_show (tvReservation);
  gtk_fixed_put (GTK_FIXED (fixed6), tvReservation, 144, 224);
  gtk_widget_set_size_request (tvReservation, 640, 320);

  image50 = create_pixmap (Reservations_Listes, "logo_parky1-removebg-preview.png");
  gtk_widget_show (image50);
  gtk_fixed_put (GTK_FIXED (fixed6), image50, 840, 224);
  gtk_widget_set_size_request (image50, 352, 288);

  comboEtat = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboEtat);
  gtk_fixed_put (GTK_FIXED (fixed6), comboEtat, 616, 96);
  gtk_widget_set_size_request (comboEtat, 205, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboEtat), _("Annulee"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboEtat), _("Validee"));

  checkStatus = gtk_check_button_new_with_mnemonic (_("Status"));
  gtk_widget_show (checkStatus);
  gtk_fixed_put (GTK_FIXED (fixed6), checkStatus, 304, 96);
  gtk_widget_set_size_request (checkStatus, 118, 24);

  checkDateDebut = gtk_check_button_new_with_mnemonic (_("Date Debut"));
  gtk_widget_show (checkDateDebut);
  gtk_fixed_put (GTK_FIXED (fixed6), checkDateDebut, 304, 136);
  gtk_widget_set_size_request (checkDateDebut, 118, 24);

  label96 = gtk_label_new (_("<u><span color=\"\n\nnavy blue\"font-weight=\"Bold\" font=\"georgia\" size=\"x-large\">  Listes de mes Reservations   </span></u>"));
  gtk_widget_show (label96);
  gtk_fixed_put (GTK_FIXED (fixed6), label96, 408, 16);
  gtk_widget_set_size_request (label96, 392, 56);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);

  btnFiltreRes = gtk_button_new ();
  gtk_widget_show (btnFiltreRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnFiltreRes, 72, 88);
  gtk_widget_set_size_request (btnFiltreRes, 120, 48);

  alignment39 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment39);
  gtk_container_add (GTK_CONTAINER (btnFiltreRes), alignment39);

  hbox45 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox45);
  gtk_container_add (GTK_CONTAINER (alignment39), hbox45);

  image44 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image44);
  gtk_box_pack_start (GTK_BOX (hbox45), image44, FALSE, FALSE, 0);

  label95 = gtk_label_new_with_mnemonic (_("Filtrer"));
  gtk_widget_show (label95);
  gtk_box_pack_start (GTK_BOX (hbox45), label95, FALSE, FALSE, 0);

  btnTriRes = gtk_button_new ();
  gtk_widget_show (btnTriRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnTriRes, 56, 600);
  gtk_widget_set_size_request (btnTriRes, 104, 37);

  alignment40 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment40);
  gtk_container_add (GTK_CONTAINER (btnTriRes), alignment40);

  hbox46 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox46);
  gtk_container_add (GTK_CONTAINER (alignment40), hbox46);

  image45 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image45);
  gtk_box_pack_start (GTK_BOX (hbox46), image45, FALSE, FALSE, 0);

  label99 = gtk_label_new_with_mnemonic (_("Trier"));
  gtk_widget_show (label99);
  gtk_box_pack_start (GTK_BOX (hbox46), label99, FALSE, FALSE, 0);

  btnAjouterFl = gtk_button_new ();
  gtk_widget_show (btnAjouterFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAjouterFl, 56, 696);
  gtk_widget_set_size_request (btnAjouterFl, 112, 40);

  alignment41 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment41);
  gtk_container_add (GTK_CONTAINER (btnAjouterFl), alignment41);

  hbox47 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox47);
  gtk_container_add (GTK_CONTAINER (alignment41), hbox47);

  image46 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image46);
  gtk_box_pack_start (GTK_BOX (hbox47), image46, FALSE, FALSE, 0);

  label100 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label100);
  gtk_box_pack_start (GTK_BOX (hbox47), label100, FALSE, FALSE, 0);

  btnModifierFl = gtk_button_new ();
  gtk_widget_show (btnModifierFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnModifierFl, 368, 632);
  gtk_widget_set_size_request (btnModifierFl, 120, 40);

  alignment45 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment45);
  gtk_container_add (GTK_CONTAINER (btnModifierFl), alignment45);

  hbox51 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox51);
  gtk_container_add (GTK_CONTAINER (alignment45), hbox51);

  image51 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image51);
  gtk_box_pack_start (GTK_BOX (hbox51), image51, FALSE, FALSE, 0);

  label104 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label104);
  gtk_box_pack_start (GTK_BOX (hbox51), label104, FALSE, FALSE, 0);

  btnAnnulerRes = gtk_button_new ();
  gtk_widget_show (btnAnnulerRes);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAnnulerRes, 664, 592);
  gtk_widget_set_size_request (btnAnnulerRes, 184, 40);

  alignment43 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment43);
  gtk_container_add (GTK_CONTAINER (btnAnnulerRes), alignment43);

  hbox49 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox49);
  gtk_container_add (GTK_CONTAINER (alignment43), hbox49);

  image48 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image48);
  gtk_box_pack_start (GTK_BOX (hbox49), image48, FALSE, FALSE, 0);

  label102 = gtk_label_new_with_mnemonic (_("Annuler Reservation"));
  gtk_widget_show (label102);
  gtk_box_pack_start (GTK_BOX (hbox49), label102, FALSE, FALSE, 0);

  btnSupprimerFl = gtk_button_new ();
  gtk_widget_show (btnSupprimerFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnSupprimerFl, 728, 688);
  gtk_widget_set_size_request (btnSupprimerFl, 120, 40);

  alignment44 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment44);
  gtk_container_add (GTK_CONTAINER (btnSupprimerFl), alignment44);

  hbox50 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox50);
  gtk_container_add (GTK_CONTAINER (alignment44), hbox50);

  image49 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image49);
  gtk_box_pack_start (GTK_BOX (hbox50), image49, FALSE, FALSE, 0);

  label103 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label103);
  gtk_box_pack_start (GTK_BOX (hbox50), label103, FALSE, FALSE, 0);

  btnAcceuilFl = gtk_button_new ();
  gtk_widget_show (btnAcceuilFl);
  gtk_fixed_put (GTK_FIXED (fixed6), btnAcceuilFl, 1024, 88);
  gtk_widget_set_size_request (btnAcceuilFl, 114, 45);

  alignment46 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment46);
  gtk_container_add (GTK_CONTAINER (btnAcceuilFl), alignment46);

  hbox52 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox52);
  gtk_container_add (GTK_CONTAINER (alignment46), hbox52);

  image53 = gtk_image_new_from_stock ("gtk-home", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image53);
  gtk_box_pack_start (GTK_BOX (hbox52), image53, FALSE, FALSE, 0);

  label106 = gtk_label_new_with_mnemonic (_("Acceuil"));
  gtk_widget_show (label106);
  gtk_box_pack_start (GTK_BOX (hbox52), label106, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) tvReservation, "row_activated",
                    G_CALLBACK (on_tvReservation_row_activated),
                    NULL);
  g_signal_connect ((gpointer) checkStatus, "toggled",
                    G_CALLBACK (on_checkStatus_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkDateDebut, "toggled",
                    G_CALLBACK (on_checkDateDebut_toggled),
                    NULL);
  g_signal_connect ((gpointer) btnFiltreRes, "clicked",
                    G_CALLBACK (on_btnFiltreRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnTriRes, "clicked",
                    G_CALLBACK (on_btnTriRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAjouterFl, "clicked",
                    G_CALLBACK (on_btnAjouterFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnModifierFl, "clicked",
                    G_CALLBACK (on_btnModifierFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAnnulerRes, "clicked",
                    G_CALLBACK (on_btnAnnulerRes_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnSupprimerFl, "clicked",
                    G_CALLBACK (on_btnSupprimerFl_clicked),
                    NULL);
  g_signal_connect ((gpointer) btnAcceuilFl, "clicked",
                    G_CALLBACK (on_btnAcceuilFl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Reservations_Listes, Reservations_Listes, "Reservations_Listes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label97, "label97");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label98, "label98");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinJourFl, "spinJourFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinMoisFl, "spinMoisFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, spinAnneeFl, "spinAnneeFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, tvReservation, "tvReservation");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image50, "image50");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, comboEtat, "comboEtat");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, checkStatus, "checkStatus");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, checkDateDebut, "checkDateDebut");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label96, "label96");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnFiltreRes, "btnFiltreRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment39, "alignment39");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image44, "image44");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label95, "label95");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnTriRes, "btnTriRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment40, "alignment40");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image45, "image45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label99, "label99");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAjouterFl, "btnAjouterFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment41, "alignment41");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image46, "image46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label100, "label100");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnModifierFl, "btnModifierFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment45, "alignment45");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox51, "hbox51");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image51, "image51");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label104, "label104");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAnnulerRes, "btnAnnulerRes");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment43, "alignment43");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox49, "hbox49");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image48, "image48");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label102, "label102");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnSupprimerFl, "btnSupprimerFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment44, "alignment44");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox50, "hbox50");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image49, "image49");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label103, "label103");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, btnAcceuilFl, "btnAcceuilFl");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, alignment46, "alignment46");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, hbox52, "hbox52");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, image53, "image53");
  GLADE_HOOKUP_OBJECT (Reservations_Listes, label106, "label106");

  return Reservations_Listes;
}

