/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *menu_Admin;
  
  
  GtkWidget *Menu_User;
  GtkWidget *Liste_de_Reservation;
  GtkWidget *Ajouter_Reservation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  menu_Admin = create_menu_Admin ();
  gtk_widget_show (menu_Admin);
  
 
  Menu_User = create_Menu_User ();
  gtk_widget_show (Menu_User);
 // Liste_de_Reservation = create_Reservations_Listes();
 // gtk_widget_show (Liste_de_Reservation);
 // Ajouter_Reservation = create_Ajouter_Reservation ();
 // gtk_widget_show (Ajouter_Reservation);

  gtk_main ();
  return 0;
}

